<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php
    $helper      = $this->helper('Lof\LazyLoad\Helper\Data');
    $imgUrl = $this->getUrl('pub/media') . 'catalog/product';
    if ($block->getInfo()) {
        $imgUrl = $this->getUrl('pub/media') . 'catalog/product' . $block->getInfo();
    } else {
        $imgUrl = '';
    }
?>
<img class="photo image lazy"
     <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
     src="<?php echo $block->getViewFileUrl('images/loader.gif') ?>"
     data-src="<?php echo $block->getImageUrl(); ?>"
     data-hover="<?php echo $imgUrl ?>"
     width="<?php /* @escapeNotVerified */ echo $block->getWidth(); ?>"
     height="<?php /* @escapeNotVerified */ echo $block->getHeight(); ?>"
     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>" />