<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper  = $this->helper('Magento\Msrp\Helper\Data');
$object  = \Magento\Framework\App\ObjectManager::getInstance();
$swatch       = $object->get('\Magento\Swatches\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>

<tr class="item-info">
    <td class="cos item" data-th="<?= $block->escapeHtml(__('Item')) ?>">
        <?php if ($block->hasProductUrl()):?>
            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
                title="<?= $block->escapeHtml($block->getProductName()) ?>"
                tabindex="-1"
                class="product-item-photo">
        <?php else:?>
            <span class="product-item-photo">
        <?php endif;?>
        <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
        <?php if ($block->hasProductUrl()):?>
            </a>
        <?php else: ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details">
            <p class="product-item-name">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </p>
            <div class="prod-line">
                <p>
                    <span><?= __('Qty') ?></span>:&nbsp;
                    <span><?= $block->getQty() ?></span>
                <p>
                    <?php if ($_options = $block->getOptionList()):?>
                        <?php foreach ($_options as $_option) : ?>
                            <?php if ($_option['label'] == 'Color'): ?>
                                <?php
                                    $_formatedOptionValue = $block->getFormatedOptionValue($_option);
                                    $swatch_value = $swatch->getSwatchesByOptionsId([$_option['option_value']]);
                                ?>
                                <span><?= __('Color') ?>:&nbsp;</span>
                                <span class="color" style="background-color: <?= $swatch_value[$_option['option_value']]['value'] ?>"></span>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif;?>
                </p>
            </div>
            <div class="prod-row">
                <p><?= $block->getUnitPriceHtml($_item) ?></p>
                <div class="field qty">
                    <button type="button" class="cart-add">
                        <svg class="icon" aria-hidden="true">
                            <use xlink:href="#icon-add"></use>
                        </svg>
                    </button>
                    <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                            name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                            data-cart-item-id="<?= /* @escapeNotVerified */ $_item->getSku() ?>"
                            value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                            type="number"
                            size="4"
                            title="<?= $block->escapeHtml(__('Qty')) ?>"
                            class="input-text qty"
                            data-validate="{required:true,'validate-greater-than-zero':true}"
                            data-role="cart-item-qty"/>
                    <button type="button" class="cart-minus">
                        <svg class="icon" aria-hidden="true">
                            <use xlink:href="#icon-minus"></use>
                        </svg>
                    </button>
                </div>
            </div>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
        <div class="prod-action">
            <?= $block->getActions($_item) ?>
        </div>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="cos msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <span class="pricing msrp">
                <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a href="javascript:;" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                    <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                </a>
            </span>
        </td>
    <?php else: ?>
        <td class="cos price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="cos color" data-th="<?= $block->escapeHtml(__('Color')) ?>">
        <?php if ($_options = $block->getOptionList()):?>
            <?php foreach ($_options as $_option) : ?>
                <?php if ($_option['label'] == 'Color'): ?>
                    <?php
                        $_formatedOptionValue = $block->getFormatedOptionValue($_option);
                        $swatch_value = $swatch->getSwatchesByOptionsId([$_option['option_value']]);
                    ?>
                    <span class="color" option-color-value="<?= $swatch_value[$_option['option_value']]['value'] ?>" style="background-color: <?= $swatch_value[$_option['option_value']]['value'] ?>"></span>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php else: ?>
            <span>-</span>
        <?php endif; ?>
    </td>
    <td class="cos qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <button type="button" class="cart cart-add">
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-add"></use>
                </svg>
            </button>
            <input id="<?= $_item->getId() ?>"
                    name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                    data-cart-item-id="<?= /* @escapeNotVerified */ $_item->getSku() ?>"
                    value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                    type="number"
                    size="4"
                    title="<?= $block->escapeHtml(__('Qty')) ?>"
                    class="input-text qty"
                    data-validate="{required:true,'validate-greater-than-zero':true}"
                    data-role="cart-item-qty"/>
            <button type="button" class="cart cart-minus">
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-minus"></use>
                </svg>
            </button>
        </div>
    </td>

    <td class="cos subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
        <div class="actions-toolbar">
            <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>