<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>

<div class="content">
    <form class="form subscribe"
        novalidate
        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
        id="newsletter-validate-detail">
        <div class="field newsletter">
            <div class="control">
                <input name="email" type="email" id="newsletter"
                            placeholder="<?= $block->escapeHtmlAttr(__('Email Address *')) ?>"
                            data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="actions">
            <button class="btn btn-green" title="<?= $block->escapeHtmlAttr(__('Join')) ?>" type="submit">
                <span><?= $block->escapeHtml(__('Join')) ?></span>
            </button>
        </div>
    </form>
    <div class="bottom">
        <p class="info"><?= __('Sign me up to receive emails on new product arrivals, specail offers and exclusive events.') ?></p>
    </div>
</div>
