<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="checkout-failure">
    <div class="checkout-box">
        <p class="con">
            <a href="javascript:;">
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-no"></use>
                </svg>
            </a>
        </p>
        <h2><?= __('Oops, something went wrong!') ?></h2>
        <p class="text"><?= __('We are unable to process your payment.') ?> </p>
        <p class="con">
            <a href="javascript:;">
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-tel"></use>
                </svg>
            </a>
        </p>
        <p class="text">
            <span><?= __('Please try again or contact customer service at') ?></span>
            <span><a href="tel: 18009550402"><?= __('1-800-955-0402') ?></span>
            <span><?= __('Daily 9:00-18:00.') ?></span>
        </p>
    </div>
</div>