<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php 
    $_product = $block->getProduct();
    $buttonTitle = __('ADD TO CART');
    $checkoutTitle = __('Buy Now');
?>
<?php if ($_product->isSaleable()): ?>
<div class="prod-form">
    <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <button type="button" class="cart-add">
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-add"></use> 
                </svg>
            </button>
            <input type="number"
                name="qty"
                id="qty"
                value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                class="input-text qty"
                data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                />
            <button type="button" class="cart-minus">
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-minus"></use>
                </svg>
            </button>
            <?= $block->getChildHtml('quick.price.final') ?>
            <?= $block->getChildHtml('quick.configuration.price.final') ?>
            <?= $block->getChildHtml('quick.price.render.bundle.customization') ?>
        </div>
        <?= $block->getChildHtml('quick.button') ?>
    <?php endif; ?>
    <div class="btn-group">
        <button type="submit"
                title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                class="action tocart"
                id="product-addtocart-button">
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-shippingcart"></use>
            </svg>
            <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
        </button>
        <button type="button"
                title="<?= /* @escapeNotVerified */ $checkoutTitle ?>"
                class="action tocheckout">
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-bag"></use>
            </svg>
            <span><?= /* @escapeNotVerified */ $checkoutTitle ?></span>
        </button>
        <button type="submit" title="<?= __('Comfirm') ?>" class="action comfirm">
            <span><?= __('Comfirm') ?></span>
        </button>
        <button type="button" title="<?= __('Cancel') ?>" class="action cancel">
            <span><?= __('Cancel') ?></span>
        </button>
    </div>
    <?php endif; ?>
    <?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#quick_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
    <?php else : ?>
    <script type="text/x-magento-init">
        {
            "#quick_addtocart_form": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
    </script>
</div>
<?php endif; ?>
