<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ __('Discount Code') ?></strong>
        <svg class="icon top" aria-hidden="true">
            <use xlink:href="#icon-top"></use>
        </svg>
        <svg class="icon down" aria-hidden="true">
            <use xlink:href="#icon-down"></use>
        </svg>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field d-flex">
                    <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?= $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?= $block->escapeHtml(__('Enter discount code')) ?>" />
                    <?php if (!strlen($block->getCouponCode())): ?>
                        <button class="action apply primary" type="button" value="<?= /* @escapeNotVerified */ __('Apply') ?>">
                            <span><?= /* @escapeNotVerified */ __('Apply') ?></span>
                        </button>
                    <?php else: ?>
                        <button  type="button" class="action cancel primary" value="<?= /* @escapeNotVerified */ __('Cancel') ?>"><span><?= /* @escapeNotVerified */ __('Cancel') ?></span></button>
                    <?php endif; ?>
                </div>
            </div>
        </form>
    </div>
</div>
