<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
?>

<div class="customer-info">
    <div class="container">
        <div class="row">
            <div class="boxes">
                <?= $block->getChildHtml() ?>
            </div>
        </div>
    </div>
</div>
