<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
?>

<div class="customer-forgotPassword">
    <?= $block->getChildHtml('cutomer_logo') ?>
    <h2 class="block-title">
        <span><?= __('Forget Your Password ?') ?></span>
    </h2>
    <div class="block-content">
        <?= $block->getChildHtml('forgotPassword') ?>
    </div>
</div>