<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
 use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $imgManager = $objectManager->get('Silk\Catalog\Block\Product\AbstractProduct');
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items owl-carousel owl-theme">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php if ($iterator++ != 1): ?></li><?php endif ?>
                        <li class="item">
                        <div class="product-item-info">
                            <?php $productImage = $block->getImage($_item, $image);?>
                            <div class="product-item-img">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                    <?= $imgManager->inventImage($_item, $image)->toHtml() ?>
                                </a>
                                <?php if ($showWishlist || $showCompare): ?>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                            <a href="javascript:;" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                <svg class="icon wishlist" aria-hidden="true">
                                                    <use xlink:href="#icon-wishlist"></use>
                                                </svg>
                                            </a>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                            <a href="javascript:;" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                <svg class="icon compare" aria-hidden="true">
                                                    <use xlink:href="#icon-compare"></use>
                                                </svg>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <a href="javascript:;" class="weltpixel-quickview" title="<?= __('Quickview') ?>" data-quickview-url="<?php echo $this->getUrl('weltpixel_quickview/catalog_product/view/id/'.$_item->getId());?>">
                                    <svg class="icon" aria-hidden="true">
                                        <use xlink:href="#icon-seek"></use>
                                    </svg>
                                    <span><?= __('Quickview') ?></span>
                                </a>
                            </div>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?php if ($templateType): ?>
                                    <div class="product-reviews-summary">
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    </div>
                                <?php endif; ?>
                                <div class="product-item-row">
                                    <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                    <?= $block->getProductDetailsHtml($_item) ?>
                                </div>
                            </div>
                        </div>
                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                            <div class="product-item-inner">
                                <div class="product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_item->getSku() ?>" data-img-url="<?= $productImage->getImageUrl() ?>" action="<?= $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button class="action tocart primary" type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                        <svg class="icon" aria-hidden="true">
                                                            <use xlink:href="#icon-shippingcart"></use>
                                                        </svg>    
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                    <a href="javascript:;" title="<?= __('Buy Now') ?>" class="action tocheckout">
                                                        <svg class="icon" aria-hidden="true">
                                                            <use xlink:href="#icon-bag"></use>
                                                        </svg>
                                                        <span><?= __('Buy Now') ?></span>
                                                    </a>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_item->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif;?>
