<?php
/**
 * Mageplaza
 *
 */
?>
<?php $availableSocials = $block->getAvailableSocials(); ?>
<?php if ($block->canShow() && sizeof($availableSocials)): ?>
    <?php foreach ($availableSocials as $key => $social): ?>
        <a href="javascript:;" class="action btn-<?= $block->getBtnKey($key) ?>"
        data-mage-init='{"socialProvider": {"url": "<?php echo $social['login_url'] ?>", "label": "<?php echo __('Login By %1', $social['label']) ?>"}}'>
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-<?= $block->getBtnKey($key) ?>"></use>
            </svg>
        </a>
    <?php endforeach; ?>
<?php endif; ?>