<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
?>

<section class="cms_block">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-sm-12 col-xs-12">
                <div class="item">
                    <p class="club">
                        <i class="dcon dcon-free"></i>
                        <span><?= __('Free Shipping') ?></span>
                    </p>
                </div>
            </div>
            <div class="col-md-4 col-sm-12 col-xs-12">
                <div class="item">
                    <p class="club">
                        <i class="dcon dcon-purchase"></i>
                        <span><?= __('30-Day Risk Free Gaurantee') ?></span>
                    </p>
                </div>
            </div>
            <div class="col-md-4 col-sm-12 col-xs-12">
                <div class="item">
                    <p class="club">
                        <i class="dcon dcon-safe"></i>
                        <span><?= __('Secure Shopping') ?></span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>