<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
?>

<section class="core-values">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="title"><?= __('Company Core Values') ?></h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="values">
                    <i class="dcon dcon-qty"></i>
                    <p class="lb">
                        <span><?= __('Quality') ?></span>
                        <svg class="icon t" aria-hidden="true">
                            <use xlink:href="#icon-arrow-t"></use>
                        </svg>
                        <svg class="icon d" aria-hidden="true">
                            <use xlink:href="#icon-arrow-d"></use>
                        </svg>
                    </p>
                    <p class="para"><?= __('Our products offer you lasting health benefits and working experiences because of life-cycle testing. All products have been rigorously tested to ensure quality.') ?></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="values">
                    <i class="dcon dcon-value"></i>
                    <p class="lb">
                        <span><?= __('Core Values') ?></span>
                        <svg class="icon t" aria-hidden="true">
                            <use xlink:href="#icon-arrow-t"></use>
                        </svg>
                        <svg class="icon d" aria-hidden="true">
                            <use xlink:href="#icon-arrow-d"></use>
                        </svg>
                    </p>
                    <p class="para"><?= __('We use robot integrated manufacturing technology to produce the most precise and best product.') ?></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="values">
                    <i class="dcon dcon-engineer"></i>
                    <p class="lb">
                        <span><?= __('Engineering') ?></span>
                        <svg class="icon t" aria-hidden="true">
                            <use xlink:href="#icon-arrow-t"></use>
                        </svg>
                        <svg class="icon d" aria-hidden="true">
                            <use xlink:href="#icon-arrow-d"></use>
                        </svg>
                    </p>
                    <p class="para"><?= __('Intelligent visual recognition and inspection technology help guarantee that all parts and products are built to perfection. Our advanced-patented gas strut mechanism offers the smoothest operation.') ?></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="values">
                    <i class="dcon dcon-satis"></i>
                    <p class="lb">
                        <span><?= __('Satisfaction Guarantee') ?></span>
                        <svg class="icon t" aria-hidden="true">
                            <use xlink:href="#icon-arrow-t"></use>
                        </svg>
                        <svg class="icon d" aria-hidden="true">
                            <use xlink:href="#icon-arrow-d"></use>
                        </svg>
                    </p>
                    <p class="para"><?= __('We stand behind our products that\'s why we offer a 30-day risk free trial with a 3 year warranty on most of our products.') ?></p>
                </div>
            </div>
        </div>
    </div>
</section>