<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Sidebar $block */
?>
<?php
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
?>
<?php if ($wishlistHelper->isAllow()) : ?>
    <div class="block block-wishlist" data-bind="scope: 'wishlist'">
        <div class="block-title">
            <strong role="heading"><?= $block->escapeHtml($block->getTitle()) ?></strong>
            <!-- ko if: wishlist().counter -->
            <span data-bind="text: wishlist().counter" class="counter"></span>
            <!-- /ko -->
        </div>
        <div class="block-content">
            <strong class="subtitle"><?= $block->escapeHtml(__('Last Added Items')) ?></strong>
            <!-- ko if: wishlist().counter -->
                <ol class="product-items owl-carousel owl-wishlist" data-bind="foreach: wishlist().items, css: {'no-display': null}, slider">
                    <li class="product-item item">
                        <div class="product-item-info">
                            <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
                                <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a data-bind="attr: { href: product_url }" class="product-item-link">
                                        <span data-bind="text: product_name"></span>
                                    </a>
                                </strong>
                                <div data-bind="html: product_price"></div>
                                <div class="product-item-actions">
                                    <!-- ko if: product_is_saleable_and_visible -->
                                        <!-- ko if: product_has_required_options -->
                                            <button type="button" data-bind="attr: {'data-post': add_to_cart_params}" class="action tocart">
                                                <svg class="icon" aria-hidden="true">
                                                    <use xlink:href="#icon-shippingcart"></use>
                                                </svg>
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <!-- /ko -->
                                        <!-- ko ifnot: product_has_required_options -->
                                            <button type="button" class="action tocart" data-bind="attr: {'data-post': add_to_cart_params}">
                                                <svg class="icon" aria-hidden="true">
                                                    <use xlink:href="#icon-shippingcart"></use>
                                                </svg>
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <!-- /ko -->
                                    <!-- /ko -->
                                    <a href="javascript:;"  data-bind="attr: {'data-post': delete_item_params}"
                                        title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>"
                                        class="btn-remove action delete">
                                        <span><?= $block->escapeHtml(__('Remove Item')) ?></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                </ol>
            <!-- /ko -->
            <!-- ko ifnot: wishlist().counter -->
                <div class="empty"><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></div>
            <!-- /ko -->
        </div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
<?php endif ?>
