<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
	<span class="form-wishlis-btn">
	    <button type="button" data-role="all-tocart" title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>" class="action tocart btn btn-dark">
	        <span><?= $block->escapeHtml(__('Add All to Cart')) ?></span>
	    </button>
    <span class="form-wishlis-btn">
<?php endif;?>
