<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
	<span class="form-wishlis-btn">
	    <button type="submit" name="do" title="<?= $block->escapeHtmlAttr(__('Update Wish List')) ?>" class="action update btn btn-dark">
	        <span><?= $block->escapeHtml(__('Update Wish List')) ?></span>
	    </button>
    </span>
<?php endif;?>
