<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="block block-search">
    <a href="javascript:;" class="action search" title="<?= __('Search') ?>">
        <svg class="icon" aria-hidden="true">
            <use xlink:href="#icon-search"></use>
        </svg>
    </a>
</div>
