<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<a href="#"
   title="<?= $block->escapeHtml(__('Remove item')) ?>"
   class="action-delete"
   data-post='<?= /* @escapeNotVerified */ $block->getDeletePostJson() ?>'>
    <svg class="icon" aria-hidden="true">
        <use xlink:href="#icon-delete"></use>
    </svg>
</a>
