<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$object  = \Magento\Framework\App\ObjectManager::getInstance();
$product = $object->get('\Magento\Catalog\Model\Product')->load($_item->getProductId());
$image   = $object->get('\Magento\Catalog\Helper\ImageFactory');
$imageUrl  = $image->create()->init($product, 'product_small_image')->setImageFile($product->getFile())->getUrl();
$data    = [];
$swatch       = $object->get('\Magento\Swatches\Helper\Data');
$_options = $block->getItemOptions();
if (!empty($_options)) {
    foreach($_options as $option){
        if ($option['label'] == 'Color')
        {
        $color   = $swatch->getSwatchesByOptionsId([$option['option_value']]);
        $data['color']  = $color[$option['option_value']]['value'];
        } else if ($option['label'] == 'Size'){
        $data['size']    = $option['value'];
        }
    }
}
?>
<tr id="order-item-row-<?= /* @escapeNotVerified */ $_item->getId(); ?>">
    <td class="col-td name name-pro" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <dl class="item-options" style="display: none;">
            <?php foreach ($_options as $_option) : ?>
                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <dd>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                            <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                        <?php else: ?>
                            <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                        <?php endif; ?>
                    </dd>
                <?php else: ?>
                    <dd>
                        <?= nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
        <div class="pro-deatil-wrapper">
            <div class="pic">
                <img src="<?php echo $imageUrl?>">
            </div>
            <div class="pro-deatil-text">
                <h4 class="title"><?= $block->escapeHtml($_item->getName()) ?></h4>
                <div class="number">Sku: <?= /* @escapeNotVerified */ $block->prepareSku($block->getSku()) ?></div>
            </div>
        </div>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col-td price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col-td color" data-th="<?= $block->escapeHtml(__('Color')) ?>">
        <?php if (!empty($data['color'])){ ?>
            <span class="circle-pro" style="background-color: <?= $data['color'] ?>"></span>
        <?php }else {?>
            <span class="color">--</span>
        <?php }?>
    </td>
    <td class="col-td qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="content" title="<?= /* @escapeNotVerified */ __('Ordered') ?> <?= /* @escapeNotVerified */ $block->getItem()->getQtyOrdered()*1 ?>"><?= /* @escapeNotVerified */ $block->getItem()->getQtyOrdered()*1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                <li class="item">
                    <span class="content" title="<?= /* @escapeNotVerified */ __('Shipped') ?> <?= /* @escapeNotVerified */ $block->getItem()->getQtyShipped()*1 ?>"><?= /* @escapeNotVerified */ $block->getItem()->getQtyShipped()*1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                <li class="item">
                    <span class="content" title="<?= /* @escapeNotVerified */ __('Canceled') ?> <?= /* @escapeNotVerified */ $block->getItem()->getQtyCanceled()*1 ?>"><?= /* @escapeNotVerified */ $block->getItem()->getQtyCanceled()*1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                <li class="item">
                    <span class="content" title="<?= /* @escapeNotVerified */ __('Refunded') ?> <?= /* @escapeNotVerified */ $block->getItem()->getQtyRefunded()*1 ?>"><?= /* @escapeNotVerified */ $block->getItem()->getQtyRefunded()*1 ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col-td subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
