<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_featuredImage = $_post->getFeaturedImage()
?>
<div class="post-view">
    <div class="post-holder">
        <img class="lazy" src="<?php echo $block->getViewFileUrl('images/loading.gif') ?>" data-src="<?php echo $_featuredImage ?>" alt="<?php echo $_postName ?>" />
        <h1 class="title"><?= $_post->getTitle() ?></h1>
        <div class="post-header">
            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
            <?php echo $this->getInfoHtml() ?>
        </div>
        <div class="post-content">
            <div class="post-description">
                <div class="post-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>