<script>
    require(["jquery", 'underscore'], function ($, _) {
        $(document).ready(function() {
            var documentPadding = 50;
            var firstAttempt = true;
            var lastHeight = 0, curHeight = 0;
            var parentBody = window.parent.document.body;

            $('.block-products-list').remove();
            $('.mfp-preloader', parentBody).css('display', 'none');
            $('.mfp-iframe-holder .mfp-content', parentBody).css('width', '100%');
            $('.mfp-iframe-scaler iframe', parentBody).animate({'opacity': 1}, 2000);
            $('.reviews-actions a').attr('target', '_parent');
            $('.product-social-links a').attr('target', '_parent');

            setInterval(function(){
                if (firstAttempt) {
                    curHeight =  $('.page-wrapper').outerHeight(true) + documentPadding;
                } else {
                    curHeight =  $('.page-wrapper').outerHeight(true);
                }
                documentHeight =  curHeight + "px";
                if ( curHeight != lastHeight ) {
                    $('.mfp-iframe-holder .mfp-content', parentBody).animate({
                        'height': documentHeight
                    }, 500);
                    lastHeight = curHeight;
                    firstAttempt = false;
                }
            }, 500);
        });

        $(document).on('ajaxComplete', function (event, xhr, settings) {
            var parentBody = window.parent.document.body;
            var cartMessage = false;
            var showShoppingCheckoutButtons  = parseInt(window.quickView.showShoppingCheckoutButtons);
            if (settings.type.match(/get/i) && _.isObject(xhr.responseJSON)) {
                var result = xhr.responseJSON;
                if (_.isObject(result.messages)) {
                    var messageLength = result.messages.messages.length;
                    var message = result.messages.messages[0];
                    if (messageLength) {
                        cartMessage = message.text;
                    }
                }
                if (_.isObject(result.cart) && _.isObject(result.messages)) {
                    var messageLength = result.messages.messages.length;
                    var message = result.messages.messages[0];
                    if (messageLength) {
                        cartMessage = message.text;
                    }
                }

                if  (cartMessage) {
                    window.parent.quickView.showMiniCartFlag = true;
                }
            }
        });
    });
</script>