<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
?>

<?= $block->getChildHtml('new_blog') ?>

<?= $block->getChildHtml('cms_block') ?>

<?= $block->getChildHtml('shop_solutions') ?>

<?= $block->getChildHtml('cms.product') ?>

<?= $block->getChildHtml('cms_review') ?>

<?= $block->getChildHtml('core_values') ?>