<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <section class="page-crumbs">
        <div class="breadcrumbs">
            <ul class="items">
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <?php if (strcmp($crumbName, 'home')): ?>
                        <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-right"></use>
                            </svg>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else: ?>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </section>
<?php endif; ?>
