<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="block <?= /* @escapeNotVerified */ $block->getBlockCss() ?>">
    <div class="title <?= /* @escapeNotVerified */ $block->getBlockCss() ?>-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?= /* @escapeNotVerified */ $block->getBlockCss() ?>", "selectorsToggleClass": "active"}}'>
        <strong><?= /* @escapeNotVerified */ $block->getBlockTitle() ?></strong>
    </div>
    <div class="content <?= /* @escapeNotVerified */ $block->getBlockCss() ?>-content" id="<?= /* @escapeNotVerified */ $block->getBlockCss() ?>">
        <div class="myboard">
            <div class="myboard-link">
                <span>Account Dashboard</span>
                <span class="myboard-arrow"><i></i></span>
            </div>
        </div>
        <div class="myboard-nav">
            <?= $block->getChildHtml() ?>
        </div>
    </div>
</div>
