<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $objManager = \Magento\Framework\App\ObjectManager::getInstance();
	$session = $objManager->create('Magento\Customer\Model\Session');
	$customerSession = $objManager->create('Magento\Customer\Model\Customer');
    $customer = $customerSession->load($session->getCustomerId());
    $group = $block->getGroupName();
    $groupCss = $block->getGroupCss();
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <div class="sections <?= /* @escapeNotVerified */ $groupCss ?>">
        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?= /* @escapeNotVerified */ $groupCss ?>-items">
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="section-item-title active <?= /* @escapeNotVerified */ $groupCss ?>-item-title" data-role="collapsible">
                    <a class="<?= /* @escapeNotVerified */ $groupCss ?>-item-switch" data-toggle="switch" href="javascript:;">
                        <svg class="icon" aria-hidden="true">
                            <use xlink:href="#icon-menu"></use>
                        </svg>
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="section-item-content active <?= /* @escapeNotVerified */ $groupCss ?>-item-content" data-role="content"><?= /* @escapeNotVerified */ $html ?></div>
            <?php endforeach;?>
            <div class="section-item-title  <?= /* @escapeNotVerified */ $groupCss ?>-item-title" data-role="collapsible">
                <a class="<?= /* @escapeNotVerified */ $groupCss ?>-item-switch" data-toggle="switch" href="javascript:;">
                    <svg class="icon" aria-hidden="true">
                        <use xlink:href="#icon-account"></use>
                    </svg>
                    <?= __ ('Account') ?>
                </a>
            </div>
            <div class="section-item-content <?= /* @escapeNotVerified */ $groupCss ?>-item-content" data-role="content">
                <ul class="ui-content">
                    <?php if($session->isLoggedIn()):?>
                        <li>
                            <a href="<?= $this->getUrl("customer/account")?>" title="<?= __("My Account"); ?>"><?= __("My Account"); ?></a>
                        </li>
                        <li>
                            <a href="<?= $this->getUrl("sales/order/history")?>" title="<?= __("My Orders"); ?>"><?= __("My Orders"); ?></a>
                        </li>
                        <li>
                            <a href="<?= $this->getUrl("wishlist")?>" title="<?= __("My Wish List"); ?>"><?= __("My Wish List"); ?></a>
                        </li>
                        <li>
                            <a href="<?= $this->getUrl("customer/account/logout")?>" title="<?= __("Log Out"); ?>"><?= __("Log Out"); ?></a>
                        </li>
                    <?php else: ?>
                        <li>
                            <a href="<?= $this->getUrl("customer/account/login")?>" title="<?= __("Log In"); ?>"><?= __("Log In"); ?></a>
                        </li>
                        <li>
                            <a href="<?= $this->getUrl("customer/account/create")?>" title="<?= __("Register"); ?>"><?= __("Register"); ?></a>
                        </li>
                        <li>
                            <a href="<?= $this->getUrl("catalog/product_compare")?>" title="<?= __("My Compare"); ?>"><?= __("My Compare"); ?></a>
                        </li>
                        <li>
                            <a href="<?= $this->getUrl("wishlist")?>" title="<?= __("My Wish List"); ?>"><?= __("My Wish List"); ?></a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
        <a href="javascript:;" class="nav close" title="Close">
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-closebox"></use>
            </svg>
        </a>
    </div>
    <div class="nav-layer"></div>
<?php endif; ?>
