<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
?>
<div class="converter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="tl"><?= __('Effortless And Stable Converter') ?></h2>
                <p><?= __('See what makes our standing desks stand out. Compared to the competition, there is no competition.') ?></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="stable">
                    <dl class="head">
                        <dt><?= __('Compare') ?></dt>
                        <dt><big><?= __('Eureka') ?></big></dt>
                        <dt><?= __('Guys') ?></dt>
                    </dl>
                    <dl>
                        <dt><?= __('Power-Adjustable Height Technology') ?></dt>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-yes"></use>
                            </svg>
                        </dd>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-no"></use>
                            </svg>
                        </dd>
                    </dl>
                    <dl>
                        <dt><?= __('Dangerous Hinged Lift Mechanics') ?></dt>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-yes"></use>
                            </svg>
                        </dd>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-no"></use>
                            </svg>
                        </dd>
                    </dl>
                    <dl>
                        <dt><?= __('Nearness to existing desktop') ?></dt>
                        <dd>3.30"</dd>
                        <dd>5"</dd>
                    </dl>
                    <dl>
                        <dt><?= __('Power-Adjustable Height Technology') ?></dt>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-yes"></use>
                            </svg>
                        </dd>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-no"></use>
                            </svg>
                        </dd>
                    </dl>
                    <dl>
                        <dt><?= __('Dangerous Hinged Lift Mechanics') ?></dt>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-yes"></use>
                            </svg>
                        </dd>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-no"></use>
                            </svg>
                        </dd>
                    </dl>
                    <dl>
                        <dt><?= __('Nearness to existing desktop') ?></dt>
                        <dd>3.30"</dd>
                        <dd>5"</dd>
                    </dl>
                    <dl>
                        <dt><?= __('Power-Adjustable Height Technology') ?></dt>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-yes"></use>
                            </svg>
                        </dd>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-no"></use>
                            </svg>
                        </dd>
                    </dl>
                    <dl>
                        <dt><?= __('Dangerous Hinged Lift Mechanics') ?></dt>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-yes"></use>
                            </svg>
                        </dd>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-no"></use>
                            </svg>
                        </dd>
                    </dl>
                    <dl>
                        <dt><?= __('Nearness to existing desktop') ?></dt>
                        <dd>3.30"</dd>
                        <dd>5"</dd>
                    </dl>
                    <dl>
                        <dt><?= __('Power-Adjustable Height Technology') ?></dt>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-yes"></use>
                            </svg>
                        </dd>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-no"></use>
                            </svg>
                        </dd>
                    </dl>
                    <dl>
                        <dt><?= __('Dangerous Hinged Lift Mechanics') ?></dt>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-yes"></use>
                            </svg>
                        </dd>
                        <dd>
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#icon-no"></use>
                            </svg>
                        </dd>
                    </dl>
                    <dl>
                        <dt><?= __('Nearness to existing desktop') ?></dt>
                        <dd>3.30"</dd>
                        <dd>5"</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>