<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                ><?= $block->escapeHtml(__($_order)) ?></option>
        <?php endforeach; ?>
    </select>
    <div data-role="sorter" class="sorter-options sorter-simulate">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <?php if ($block->isOrderCurrent($_key)): ?>
                <cite><?= $block->escapeHtml(__($_order)) ?></cite>
            <?php endif; ?>
        <?php endforeach; ?>
        <ul class="sorter-layer">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <li 
                    <?php if ($block->isOrderCurrent($_key)): ?>
                        class="selected"
                    <?php endif; ?>
                >
                    <p key="<?= /* @escapeNotVerified */ $_key ?>"><?= $block->escapeHtml(__($_order)) ?></p>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="javascript:;" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-arrow-down"></use>
            </svg>
        </a>
    <?php else: ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="javascript:;" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-arrow-up"></use>
            </svg>
        </a>
    <?php endif; ?>
</div>
