<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
?>

<section class="page-crumbs">
    <div class="breadcrumbs">
        <ul class="items">
            <li class="item">
                <a href="<?= $this->getUrl('/') ?>" title="<?= __('Go to Home Page') ?>"><?= __('Home') ?></a>
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-right"></use>
                </svg>
            </li>
            <li class="item">
                <strong><?= $block->escapeHtml($viewModel->getProductName()); ?></strong>
            </li>
        </ul>
    </div>
</section>
