<div class="btn-quick">
    <button type="button" class="action cart" title="<?= __('Add To Cart') ?>">
        <svg class="icon" aria-hidden="true">
            <use xlink:href="#icon-shippingcart"></use> 
        </svg> 
        <span><?= __('Add To Cart') ?></span>
    </button>
    <button type="submit" class="action checkout" title="<?= __('Buy Now') ?>">
        <svg class="icon" aria-hidden="true">
            <use xlink:href="#icon-bag"></use>
        </svg>
        <span><?= __('Buy Now') ?></span>
    </button>
</div>