<a href="javascript:;" class="open-filter">
    <svg class="icon left" aria-hidden="true">
        <use xlink:href="#icon-arrow-left"></use>
    </svg>
    <svg class="icon right" aria-hidden="true">
        <use xlink:href="#icon-arrow-right"></use>
    </svg>
</a>
<a href="javascript:;" class="close-filter">
    <svg class="icon" aria-hidden="true">
        <use xlink:href="#icon-closebox"></use> 
    </svg>
</a>