<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Silk\Catalog\Block\Title */
?>

<div class="page-title">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $block->getTitle() ?></h1>
            </div>
        </div>
    </div>
</div>