<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>

<form class="form forget-password"
    action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
    method="post"
    id="form-validate"
    data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset forget" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <h2><?= __('Forget Your Password') ?></h2>
        <div class="form-group">
            <p class="note"><?= $block->escapeHtml(__('Just enter your e-mail address below and we\'ll send you a link with instructions to reset your password. If you need additional assistance, Please contact our customer service.')) ?></p>
        </div>
        <div class="form-group required">
            <label for="email_address"><?= $block->escapeHtml(__('Email Address')) ?></label>
            <input type="email" name="email" alt="email" id="email_address" class="form-control" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" placeholder="<?= __('Email Address') ?>" data-validate="{required:true, 'validate-email':true}" />
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
        <div class="btn-group">
            <button type="submit" class="btn btn-dark">
                <span><?= __('Submit') ?></span>
            </button>
        </div>
    </fieldset>
</form>
