<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>

<div class="col-md-6 col-sm-6 col-sx-12">
    <div class="customer-login">
        <?= $block->getChildHtml('cutomer_logo') ?>
        <h2 class="block-title">
            <span><?= __('Log In') ?></span>
        </h2>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login"
                action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                method="post"
                id="login-form"
                data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey') ?>
                <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="form-group required">
                        <label for="email"><?= $block->escapeHtml(__('Email Address')) ?></label>
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control" placeholder="<?= $block->escapeHtmlAttr(__('Email Address')) ?>" data-validate="{required:true, 'validate-email':true}" />
                    </div>
                    <div class="form-group required">
                        <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="form-control" id="pass" placeholder="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}" />
                    </div>
                    <div class="form-check">
                        <input type="checkbox" id="remember" class="form-check-input" />
                        <label class="form-check-label" for="remember"><?= __('Remember Me') ?></label>
                    </div>
                    <div class="btn-group">
                        <button type="submit" class="btn btn-dark">
                            <span><?= $block->escapeHtml(__('Login')) ?></span>
                        </button>
                    </div>
                    <div class="d-flex justify-content-between">
                        <a class="action remind" href="<?= $this->getUrl("customer/account/create")?>">
                            <span><?= $block->escapeHtml(__('Register')) ?></span>
                        </a>
                        <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
                            <span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span>
                        </a>
                    </div>
                    <div class="social">
                        <div class="d-flex justify-content-between">
                            <p class="methods"><?= __('Other Login Methods') ?></p>
                            <p class="media">
                                <?= $block->getChildHtml('social-login') ?>
                            </p>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
