<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
?>

<div class="prod-faq">
    <h1><?= __('Frequently Asked Questions') ?></h1>
    <div class="item">
        <h3><?= __('CUSTOMER SUPPORT FAQS') ?></h3>
        <ul>
            <li>
                <a href="javascript:;" class="link-faq">
                    <span>Product Vedio ?</span>
                    <svg class="icon top">
                        <use xlink:href="#icon-top"></use>
                    </svg>
                    <svg class="icon down">
                        <use xlink:href="#icon-down"></use>
                    </svg>
                </a>
                <div class="menu">
                    <div class="row">
                        <div class="col-md-6">
                            <video class="video" width="100%" height="400" 
                                src="https://vimeo.com/273185430" 
                                controls="controls" 
                                preload="none" 
                                webkit-playsinline="true" 
                                playsinline="true" 
                                x-webkit-airplay="allow" 
                                x5-video-player-type="h5" 
                                x5-video-player-fullscreen="true" 
                                x5-video-orientation="portraint"></video>
                        </div>
                        <div class="col-md-6">
                            <video class="video" width="100%" height="400" 
                                src="https://vimeo.com/276206841" 
                                controls="controls" 
                                preload="none" 
                                webkit-playsinline="true" 
                                playsinline="true" 
                                x-webkit-airplay="allow" 
                                x5-video-player-type="h5" 
                                x5-video-player-fullscreen="true" 
                                x5-video-orientation="portraint"></video>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <a href="javascript:;" class="link-faq">
                    <span>IS SHIPPING FREE ?</span>
                    <svg class="icon top">
                        <use xlink:href="#icon-top"></use>
                    </svg>
                    <svg class="icon down">
                        <use xlink:href="#icon-down"></use>
                    </svg>
                </a>
                <div class="menu">
                    <p>We ship anywhere in the Continental U.S. (excludes Alaska and Hawaii) for free.</p>
                </div>
            </li>
            <li>
                <a href="javascript:;" class="link-faq">
                    <span>DO YOU OFFER INTERNATIONAL SHIPPING ?</span>
                    <svg class="icon top">
                        <use xlink:href="#icon-top"></use>
                    </svg>
                    <svg class="icon down">
                        <use xlink:href="#icon-down"></use>
                    </svg>
                </a>
                <div class="menu">
                    <p>We ship overseas, however shipping charges may incur.</p>
                </div>
            </li>
            <li>
                <a href="javascript:;" class="link-faq">
                    <span>DO YOU OFFER A WARRANTY ON THE EUREKA DESK ?</span>
                    <svg class="icon top">
                        <use xlink:href="#icon-top"></use>
                    </svg>
                    <svg class="icon down">
                        <use xlink:href="#icon-down"></use>
                    </svg>
                </a>
                <div class="menu">
                    <p>Each Eureka Desk comes with a best-in-class 3-year limited warranty. To learn more, for more information please visit: www.eurekaergonomic.com/warranty.</p>
                </div>
            </li>
            <li>
                <a href="javascript:;" class="link-faq">
                    <span>DOES THE EUREKA DESK REQUIRE ANY MAINTENANCE ?</span>
                    <svg class="icon top">
                        <use xlink:href="#icon-top"></use>
                    </svg>
                    <svg class="icon down">
                        <use xlink:href="#icon-down"></use>
                    </svg>
                </a>
                <div class="menu">
                    <p>The Eureka Desk does not require any maintenance! Use a damp cloth to clean the surface for a simple wipe down to keep your desk clean and tidy. Please do not use any chemicals or harsh abrasives as they may damage the finish.</p>
                </div>
            </li>
            <li>
                <a href="javascript:;" class="link-faq">
                    <span>FOR FURTHER INFORMATION ?</span>
                    <svg class="icon top">
                        <use xlink:href="#icon-top"></use>
                    </svg>
                    <svg class="icon down">
                        <use xlink:href="#icon-down"></use>
                    </svg>
                </a>
                <div class="menu">
                    <p>For further information please feel free to contact our support or sales team at (844) 416-2090. You can always Live Chat during office hours for the quickest response.</p>
                </div>
            </li>
            <li>
                <a href="javascript:;" class="link-faq">
                    <span>CAN I FIT TWO MONITORS ON THE EUREKA DESK ?</span>
                    <svg class="icon top">
                        <use xlink:href="#icon-top"></use>
                    </svg>
                    <svg class="icon down">
                        <use xlink:href="#icon-down"></use>
                    </svg>
                </a>
                <div class="menu">
                    <p>Yes of course! The workspace available on the Eureka Desk can fit up to two 21” monitors side-by-side.</p>
                </div>
            </li>
            <li>
                <a href="javascript:;" class="link-faq">
                    <span>DO I NEED A WIRELESS MOUSE KEYBOARD? CAN I USE A WIRED MOUSE KEYBOARD ?</span>
                    <svg class="icon top">
                        <use xlink:href="#icon-top"></use>
                    </svg>
                    <svg class="icon down">
                        <use xlink:href="#icon-down"></use>
                    </svg>
                </a>
                <div class="menu">
                    <p>If using wired products on the Eureka Desk, we recommend to use a wire length of 5 feet or longer to ensure that the desk can be raised without pulling.</p>
                </div>
            </li>
        </ul>
    </div>
</div>