<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php 
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>

<div class="prod-param">
    <div class="container">
        <?= $_helper->productAttribute($_product, $_product->getSpecifications(), 'specifications');?>
    </div>
</div>